### ISSUE TITLE
Some pandas function is deprecated

### ISSUE THREAD

**Issue by SWittouck** [SWittouck/SCARAP#16]
SCARAP gives the following warning: 

`/.../SCARAP/src/scarap/readerswriters.py:107: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.`

**Comment by TomEile** [comment]
you could change in line 107 of the /SCARAP/src/scarap/readerswriters.py the following line to remove this warning:

`genes = genes.append(genes_genome)`
to 
`genes = pd.concat([genes,genes_genome])`

**Comment by SWittouck** [comment]
Thanks for the suggestion @TomEile !

Fixed.
