### ISSUE TITLE
Unrecongized argumets: ./outputfolder

### ISSUE THREAD

**Issue by D-Git-Bit** [SWittouck/SCARAP#30]
Hi,

I have followed the instructions to download and install SCARAP as detailed in the manual. Using  'scarap core ./inputfaas ./outputfolder -t 16' I am getting the following error:

scarap: error: unrecognized arguments: ./outputfolder.

How can I fix this?

Thank you!

**Comment by SWittouck** [comment]
Hi! 

The command you mentioned should normally work (I just tested it to be 100% sure).

What version of SCARAP are you using? And what do you get when you execute `scarap core -h`? 

Stijn

**Comment by SWittouck** [comment]
Hi, 

OK that already looks good! 

The only thing that could have caused your error is too many positional arguments. For example, if you typed `scarap core ./ inputfaas ./outputfolder -t 16` (with a space between "./" and "inputfaas"). 

Can you run your command without "./" just to be sure? --> `scarap core inputfaas outputfolder -t 16`

Cheers,
Stijn

**Comment by D-Git-Bit** [comment]
You are right! I though I had tried everything! it works without "./"!

Many thanks!

**Comment by SWittouck** [comment]
Great to hear! Good luck with the results!
